#!/bin/bash

#
# https://raw.githubusercontent.com/golang/vscode-go/master/src/goTools.ts
#

export GO111MODULE=on
export GOPROXY=https://goproxy.cn

# gocode - Auto-completion, does not work with modules
go get -u -v github.com/mdempsky/gocode

# gocode-gomod - Auto-completion, works with modules
go get -u -v github.com/stamblerre/gocode

# gopkgs - Auto-completion of unimported packages & Add Import feature
go get -u -v github.com/uudashr/gopkgs/v2/cmd/gopkgs

# go-outline - Go to symbol in file
go get -u -v github.com/ramya-rao-a/go-outline

# go-symbols - Go to symbol in workspace
go get -u -v github.com/acroca/go-symbols

# guru - Find all references and Go to implementation of symbols
go get -u -v golang.org/x/tools/cmd/guru

# gorename - Rename symbols
go get -u -v golang.org/x/tools/cmd/gorename

# gomodifytags - Modify tags on structs
go get -u -v github.com/fatih/gomodifytags

# goplay - The Go playground
go get -u -v github.com/haya14busa/goplay/cmd/goplay

# impl - Stubs for interfaces
go get -u -v github.com/josharian/impl

# gotype-live - Show errors as you type
go get -u -v github.com/tylerb/gotype-live

# godef - Go to definition
go get -u -v github.com/rogpeppe/godef

# gogetdoc - Go to definition & text shown on hover
go get -u -v github.com/zmb3/gogetdoc

# goimports - Formatter
go get -u -v golang.org/x/tools/cmd/goimports

# goreturns - Formatter
go get -u -v github.com/sqs/goreturns

# goformat - Formatter
go get -u -v winterdrache.de/goformat/goformat

# golint - Linter
go get -u -v golang.org/x/lint/golint

# gotests - Generate unit tests
go get -u -v github.com/cweill/gotests/...

# staticcheck - Linter
go get -u -v honnef.co/go/tools/...

# golangci-lint - Linter
go get -u -v github.com/golangci/golangci-lint/cmd/golangci-lint

# revive - Linter
go get -u -v github.com/mgechev/revive

# gopls - Language Server from Google
go get -u -v golang.org/x/tools/gopls

# dlv - Debugging
go get -u -v github.com/go-delve/delve/cmd/dlv

# fillstruct - Fill structs with defaults
go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct

# godoctor - Extract to functions and variables
go get -u -v github.com/godoctor/godoctor
